### ISSUE TITLE
SSLError :: CERTIFICATE_VERIFY_FAILED

### ISSUE THREAD

**Issue by adriansev** [cerndb/cern-sso-python#1]
Hi! I am trying to use cern-get-sso-cookie.py with the certificate (as i am no able to get a kerberos ticket) but i get this : 
```
INFO  root Using SSL certificate file cerncert.pem and key cerncert.key
INFO  cern_sso Fetching URL: https://alice-logbook.cern.ch/logbook/date_online.php?p_cont=rqfc&p_rsob=l.run&p_rsob_dir=DESC&prsf_rtype=PHYSICS%2C&prsf_rpart=%2C28&pqff_rq=Good+run%2C0&p_rspn=1&prsf_rts=01/11/2017%2007:00:00,02/11/2017%2007:00:00
Traceback (most recent call last):
  File "/home/adrian/.local/bin/cern-get-sso-cookie.py", line 101, in <module>
    cookiejar=cookiejar)
  File "/home/adrian/.local/lib/python2.7/site-packages/cern_sso.py", line 165, in cert_sign_on
    auth_url_fragment=u"auth/sslclient/")
  File "/home/adrian/.local/lib/python2.7/site-packages/cern_sso.py", line 48, in _init_session
    r1 = s.get(url, timeout=DEFAULT_TIMEOUT_SECONDS)
  File "/home/adrian/.local/lib/python2.7/site-packages/requests/sessions.py", line 521, in get
    return self.request('GET', url, **kwargs)
  File "/home/adrian/.local/lib/python2.7/site-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/adrian/.local/lib/python2.7/site-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/home/adrian/.local/lib/python2.7/site-packages/requests/adapters.py", line 506, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='alice-logbook.cern.ch', port=443): Max retries exceeded with url: /logbook/date_online.php?p_cont=rqfc&p_rsob=l.run&p_rsob_dir=DESC&prsf_rtype=PHYSICS%2C&prsf_rpart=%2C28&pqff_rq=Good+run%2C0&p_rspn=1&prsf_rts=01/11/2017%2007:00:00,02/11/2017%2007:00:00 (Caused by SSLError(SSLError(1, u'[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:579)'),))
```

this is a centos 7, and i have:
cern-sso (0.1.1)
python-cern-sso-krb (1.3.3)
requests (2.18.4)
requests-kerberos (0.12.0)

the certificate is a cern certificate and the key file have no password... i imagine that it tries to verify the CERN CA cert but i don't know how to provide that from user side (i try to create an application that assumes no root access on the machine)

Thank you!
Adrian

**Comment by amandasystems** [comment]
Hi,

I was a technical student during 2017 and am no longer at CERN. I would love to help you, but I don't have access to machines to test anything. I can however give you a few pointers, and if you try some of the things, I can help you from where I am to the best of my effort.

The problem is (probably) not exactly that it is trying to verify the CERN CA, It's the signatures provided by the server itself that doesn't verify, either because they are self-signed (which I hope they are not), or more likely because they are signed by the CERN CA and a) your system or b) the Python requests module doesn't have access to them.

I think there should be a copy of this repository on GitLab (but I cannot verify as I don't have access), if you have access to that, and that repository uses a CI job to run tests. If you can find it, see what kind of configuration setup the CI job has.

Also, there might be something for you in [Requests' advanced usage section of the manual](http://docs.python-requests.org/en/master/user/advanced/).

PS You probably shouldn't write Python 2, [it's going to be end-of-life in 2020](https://pythonclock.org/).

**Comment by amandasystems** [comment]
Also, it seems @icot still has his eye on this repository, so you might want to talk to him if he doesn't answer here.
